const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Tween.Acts.TweenOneProperty
	];
};
self.C3_JsPropNameTable = [
	{Fade: 0},
	{bg: 0},
	{papan: 0},
	{ukuranx: 0},
	{ukurany: 0},
	{Tween: 0},
	{play: 0},
	{Touch: 0},
	{p: 0},
	{m: 0},
	{perof: 0},
	{back: 0},
	{h: 0},
	{mat: 0},
	{Sprite: 0},
	{home: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{stk: 0},
	{bgGame: 0},
	{Solid: 0},
	{b1: 0},
	{b2: 0},
	{b3: 0},
	{kepalaO: 0},
	{Platform: 0},
	{kpl: 0},
	{Sprite4: 0},
	{tkanan: 0},
	{tkiri: 0},
	{latas: 0},
	{DragDrop: 0},
	{Text: 0},
	{text1: 0}
];

self.InstanceType = {
	bg: class extends self.ISpriteInstance {},
	papan: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	p: class extends self.ISpriteInstance {},
	m: class extends self.ISpriteInstance {},
	perof: class extends self.ISpriteInstance {},
	back: class extends self.ISpriteInstance {},
	h: class extends self.ISpriteInstance {},
	mat: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	stk: class extends self.ISpriteInstance {},
	bgGame: class extends self.ISpriteInstance {},
	b1: class extends self.ISpriteInstance {},
	b2: class extends self.ISpriteInstance {},
	b3: class extends self.ISpriteInstance {},
	kepalaO: class extends self.ISpriteInstance {},
	kpl: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	tkanan: class extends self.ISpriteInstance {},
	tkiri: class extends self.ISpriteInstance {},
	latas: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	text1: class extends self.ISpriteInstance {}
}